using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OrderSystem.Domain.Entities;
using OrderSystem.DTOs;
using OrderSystem.Infrastructure;

namespace OrderSystem.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class ProductsController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // 1. CREATE - Register a new product in the catalog
        [HttpPost]
        public async Task<IActionResult> Create([FromBody] AddProductDto dto)
        {
            // The ID is automatically generated by the Database (Identity)
            var product = new Product(dto.Name, dto.Price);
            
            _context.Products.Add(product);
            await _context.SaveChangesAsync();

            return Ok(product);
        }

        // 2. READ - List all products in the catalog
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var products = await _context.Products.ToListAsync();
            return Ok(products);
        }

        // 3. READ BY ID - Get details of a specific product
        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(int id)
        {
            var product = await _context.Products.FindAsync(id);

            if (product == null)
                return NotFound("Product not found in the catalog.");

            return Ok(product);
        }

        // 4. UPDATE - Edit an existing product's name or price
        [HttpPut("{id}")]
        public async Task<IActionResult> Update(int id, [FromBody] AddProductDto dto)
        {
            var product = await _context.Products.FindAsync(id);

            if (product == null)
                return NotFound("Product not found.");

            // Update data (The ID remains the same)
            product.Name = dto.Name;
            product.Price = dto.Price;

            await _context.SaveChangesAsync();
            return Ok("Product updated successfully.");
        }

        // 5. DELETE - Remove a product from the catalog
        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _context.Products.FindAsync(id);

            if (product == null)
                return NotFound("Product not found.");

            _context.Products.Remove(product);
            await _context.SaveChangesAsync();

            return Ok("Product removed from the catalog.");
        }
    }
}